# Generated by Django 3.1.7 on 2021-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TASK',
            fields=[
                ('TASK_ID', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('STATUS', models.TextField()),
                ('ADDRESS', models.TextField()),
            ],
        ),
    ]
